version: 2
jobs:
  build:
    working_directory: ~/flyve_mdm
    docker:
      # Android the primary container
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  validate_running: &validate_running
    run:
      name: Validate running
      command: source ci/scripts/validate_running.sh

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  ## Dependencies
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: bundle check || bundle install --path vendor/bundle

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  # Test Instrumentation with Android 4.1 JELLY_BEAN API 16
  test_instrumentation:
    working_directory: ~/flyve_mdm
    docker:
      # Android the primary container
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - *validate_running
      - *restore_gradle_cache
      - *ruby_dependencies
      - *android_dependencies
      - *save_gradle_cache
      - run:
          name: Create debug apk
          command: ./gradlew assembleDebug assembleAndroidTest
      - run:
          name: Run Tests on Firebase test lab
          command: source ci/scripts/google_cloud.sh

  screenshot_api_16:
      working_directory: ~/flyve_mdm
      docker:
          - image: circleci/android:api-26-alpha
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Setup environment
            command: source ci/scripts/ci_setup.sh
        - run:
            name: Update version and code
            command: source ci/scripts/ci_updateversion.sh
        - run:
            name: Update about information
            command: source ci/scripts/ci_about.sh
        - run:
            name: Setup emulator
            command: sdkmanager "system-images;android-16;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
        - run:
            name: Launch emulator
            command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
            background: true
        - run:
            name: Wait emulator
            command: |
              # wait for it to have booted
              circle-android wait-for-boot
              # unlock the emulator screen
              sleep 30
              adb shell input keyevent 82
        - run:
            name: Assemble Android Tests
            command: ./gradlew assembleDebug assembleAndroidTest
        - run:
            name: Run Fastlane Screengrab
            command: fastlane screengrab
        - run:
            name: send screenshot to gh-pages
            command: source ci/scripts/ci_push_screenshot.sh
        - store_artifacts:
            path: fastlane/metadata
            destination: screenshot
        - save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  deploy_beta:
    working_directory: ~/flyve_mdm
    docker:
      # Android the primary container
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup environment
          command: source ci/scripts/ci_setup.sh
      - run:
          name: Deploy Beta
          command: source ci/scripts/ci_deploy_beta.sh
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  deploy_production:
      working_directory: ~/flyve_mdm
      docker:
        # Android the primary container
        - image: circleci/android:api-26-alpha
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Setup environment
            command: source ci/scripts/ci_setup.sh
        - run:
            name: Deploy production
            command: source ci/scripts/ci_deploy_production.sh
        - save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  documentation:
      working_directory: ~/flyve_mdm
      docker:
        # Android the primary container
        - image: circleci/android:api-26-alpha
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Setup environment
            command: source ci/scripts/ci_setup.sh
        - run:
            name: Setup emulator
            command: sdkmanager "system-images;android-16;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
        - run:
            name: Launch emulator
            command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
            background: true
        - run:
            name: Wait emulator
            command: |
              # wait for it to have booted
              circle-android wait-for-boot
              # unlock the emulator screen
              sleep 30
              adb shell input keyevent 82
        - run:
            name: Generate documentation
            command: source ci/scripts/ci_documentation.sh
        - save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
#      - test_instrumentation:
#          context: org-global
#          requires:
#            - build
#          filters:
#            branches:
#              ignore:
#                - master
      - deploy_beta:
          requires:
            # - test_instrumentation
          filters:
            branches:
              only:
                - develop
      - documentation:
          requires:
            # - test_instrumentation
          filters:
            branches:
              only:
                - develop
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only:
                - master